"""Add plant archive fields

Revision ID: 74a48ee8cc04
Revises: 
Create Date: 2024-11-30 14:29:46.191077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a48ee8cc04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('archive_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archive_reason', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('archive_notes', sa.Text(), nullable=True))
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_plant_profile_image', 'plant_image', ['profile_image_id'], ['id'])

    with op.batch_alter_table('plant_image', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('plant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_image', schema=None) as batch_op:
        batch_op.alter_column('plant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plant_profile_image', type_='foreignkey')
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('archive_notes')
        batch_op.drop_column('archive_reason')
        batch_op.drop_column('archive_date')
        batch_op.drop_column('is_archived')
        batch_op.drop_column('profile_image_id')

    # ### end Alembic commands ###
