"""Add monitored_plant_ids to User model

Revision ID: bea408b98712
Revises: 4a9f9968e991
Create Date: 2024-11-30 17:59:57.570151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea408b98712'
down_revision = '4a9f9968e991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitored_plant_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('monitored_plant_ids')

    # ### end Alembic commands ###
